baseurl = "/" # Hostname (and path) to the root.
title = "Yusuke Ishimi" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Yusuke Ishimi" # Author's name.
    info = "WEB AND APPS ENGINEER" # Author's job title or info.
    description = "Yusuke Ishimi's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "Enter a text here." # Add footer content
    fixedbarContent = "Do you want to know me more private?→" # Add fixedbar content
    fixedbarContentAfter = "Thank You! Please share it if you like it→" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = true  # new add
    enableFacebookShare = true # new add
    enableHatenaShare = true   # new add
    enableLineShare = true     # new add
    enableLinkedInShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.
[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        title = "Abel José SÁnchez Alba"

        # You can configure the theme parameter for each language. 
        [languages.en.params]
        author = "Abel José Sánchez Alba"
        info = "SOFTWARE ENGINEER & MATHEMATICIAN"
        description = "Abel's personal website"
        keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "About"
        weight = 1.0
        url = "about"

        [[languages.en.menu.main]]
        name = "Education"
        weight = 2.0
        url = "education"

        [[languages.en.menu.main]]
        name = "Experience"
        weight = 3.0
        url = "experience"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 2.0
        url = "projects"


    [languages.es]
        languagename = "Spanish"
        title = "Abel José Sánchez Alba"

        [languages.es.params]
            author = "Abel José Sánchez ALba"
            description = "Pagina personal de Abel José"
            keywords = "blog,developer, ingeniero, matemático"
            info = "INGENIERO INFORMÁTICO & MATEMÁTICO"

        [languages.es.menu]

            [[languages.es.menu.main]]
            name = "Sobre mí"
            weight = 1.0
            url = "es/about"

            [[languages.es.menu.main]]
            name = "Educación"
            weight = 2.0
            url = "es/education"

            [[languages.es.menu.main]]
            name = "Experiencia"
            weight = 3.0
            url = "es/experience"

            [[languages.es.menu.main]]
            name = "Proyectos"
            weight = 4.0
            url = "es/projects"

            


# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/ajalba"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/abel-jose-sanchez-alba-a1753a1b3/"
[[params.social]]
    # If icon is not set, Text is displayed.
    name = "LinkedIn"
    weight = 4
    url = "https://www.linkedin.com/in/naro143/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"
